---
## Boolean conditional check for Installing Apache
- name: Install Apache Web Server
  apt:
    name: apache2
    state: present
  when: install_apache_flag 



## Print the OS family, Distribution version and Kernel
- name: Debug OS family, Distribution version and Kernel
  debug:
    msg:
      - "OS Family: {{ ansible_facts['os_family'] }}"
      - "Distribution Major Version: {{ ansible_facts['distribution_major_version'] }}"
      - "Kernel: {{ ansible_facts['kernel'] }}"



## Putting multiple conditions using ansible_facts
- name: Combine conditions using ansible_facts
  debug:
    msg:
      - "OS Family: {{ ansible_facts['os_family'] }}"
      - "Distribution Major Version: {{ ansible_facts['distribution_major_version'] }}"

  when:
    - ansible_facts['os_family'] == "Debian"
    - ansible_facts['distribution_major_version'] == "24"

## Using and
- name: Combine conditions using 'and'
  debug:
    msg:
      "Both the conditions are true"
  when:
    - ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] == "24"

## Register a variable in conditional statement
- name: Register a variable
  ansible.builtin.command: cat /home/pratiksha/test_file.txt
  register: test_file_content

- name: Use the variable in a conditional statement
  debug:
    var: test_file_content.stdout
  when: test_file_content.stdout.find("Hi") != -1

## When with loop
- name: Run with items > 5
  ansible.builtin.command: echo "Item is {{ item }}"
  loop: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  when:
    - item > 5

## Conditionals based on ansible_facts
- name: Using ansible_facts in conditionals
  debug:
    msg: "This is a Debian System"
  when: ansible_facts['os_family'] == "Debian"